version: '3.1'
services:
    redis:
        image: 'redis:alpine'

    mysql:
        image: 'mysql:8.0'
        working_dir: /app
        volumes:
            - db:/var/lib/mysql
            - '.:/app'
        environment:
            - MYSQL_ROOT_PASSWORD=P@ssword
            - MYSQL_DATABASE=app
            - MYSQL_USER=user
            - MYSQL_PASSWORD=P@assword
        ports:
            - '61002:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /app
        volumes:
            - '.:/app'
            - './deployment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '61000:80'

    php-fpm:
        build: deployment/php-fpm
        working_dir: /app
        volumes:
            - '.:/app'
            - './deployment/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
volumes:
    db:
